version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: auth-postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data:
